### ISSUE TITLE
Traceback from handling new package

### ISSUE THREAD

**Issue by phracek** [fedora-infra/the-new-hotness#82] opened 2015-10-19 14:08 UTC
During testing rebase-helper I have received this traceback

~~~
[2015-10-19 12:49:44][    fedmsg    INFO] Handling koji scratch msg u'2015-3aa41d6e-f045-4cad-a625-0ede6ec5900a'
[2015-10-19 12:49:45][    fedmsg    INFO] Considering new package u'mozjs38' with u'https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey'
[2015-10-19 12:49:45][    fedmsg    INFO] Looking for u'mozjs38' via 'https://release-monitoring.org/api/projects/?homepage=https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey'
[2015-10-19 12:49:45][    fedmsg    INFO] Saw 0 matching projects on anitya.  Adding.
[2015-10-19 12:49:45][    fedmsg    INFO] Attempting to login to anitya
[2015-10-19 12:49:48][    fedmsg   ERROR] {'body': {u'username': u'apache', u'certificate': u'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVUakNDQTdlZ0F3SUJBZ0lDQVQ0d0RRWUpL\nb1pJaHZjTkFRRUZCUUF3Z2FBeEN6QUpCZ05WQkFZVEFsVlQKTVFzd0NRWURWUVFJRXdKT1F6RVFN\nQTRHQTFVRUJ4TUhVbUZzWldsbmFERVhNQlVHQTFVRUNoTU9SbVZrYjNKaApJRkJ5YjJwbFkzUXhE\nekFOQmdOVkJBc1RCbVpsWkcxelp6RVBNQTBHQTFVRUF4TUdabVZrYlhObk1ROHdEUVlEClZRUXBF\nd1ptWldSdGMyY3hKakFrQmdrcWhraUc5dzBCQ1FFV0YyRmtiV2x1UUdabFpHOXlZWEJ5YjJwbFkz\nUXUKYjNKbk1CNFhEVEUwTURReU16RTBNekF3TUZvWERUSTBNRFF5TURFME16QXdNRm93Z2R3eEN6\nQUpCZ05WQkFZVApBbFZUTVFzd0NRWURWUVFJRXdKT1F6RVFNQTRHQTFVRUJ4TUhVbUZzWldsbmFE\nRVhNQlVHQTFVRUNoTU9SbVZrCmIzSmhJRkJ5YjJwbFkzUXhEekFOQmdOVkJBc1RCbVpsWkcxelp6\nRXRNQ3NHQTFVRUF4TWtjR3RuWkdJdGNHdG4KWkdJd01pNXdhSGd5TG1abFpHOXlZWEJ5YjJwbFkz\nUXViM0puTVMwd0t3WURWUVFwRXlSd2EyZGtZaTF3YTJkawpZakF5TG5Cb2VESXVabVZrYjNKaGNI\nSnZhbVZqZEM1dmNtY3hKakFrQmdrcWhraUc5dzBCQ1FFV0YyRmtiV2x1ClFHWmxaRzl5WVhCeWIy\ncGxZM1F1YjNKbk1JR2ZNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0R05BRENCaVFLQmdRQ3AKekkvVnp4\nTXZpRWk2SlRqendoc0tUYm1TQ1UrdnpyeUlDbm9heWgxVktQdlFtYUViaFo0bkIwVjA1NU5DYUd3\nZgphUzJsc2VHWEdYL2hFVG5LTTQ4ditYZDVRZzZkNCtYdENLOTZNdGJKYVdTTzdzbnNYa3VjOGli\nTlIzTzVNL0hFCmc2MU14YWdiZE1CcndMbWZWSDVWUzQ2T1grMk11RUt2aXhRMC9IUjlCUUlEQVFB\nQm80SUJWekNDQVZNd0NRWUQKVlIwVEJBSXdBREF0QmdsZ2hrZ0JodmhDQVEwRUlCWWVSV0Z6ZVMx\nU1UwRWdSMlZ1WlhKaGRHVmtJRU5sY25ScApabWxqWVhSbE1CMEdBMVVkRGdRV0JCU3E1QTNacVJ4\na0tySVpldHMwZXhOb3FxYWczRENCMVFZRFZSMGpCSUhOCk1JSEtnQlJyUUZyNUVnaUpXZWRaNVFY\nMUFoMEtUbjhVQUtHQnBxU0JvekNCb0RFTE1Ba0dBMVVFQmhNQ1ZWTXgKQ3pBSkJnTlZCQWdUQWs1\nRE1SQXdEZ1lEVlFRSEV3ZFNZV3hsYVdkb01SY3dGUVlEVlFRS0V3NUdaV1J2Y21FZwpVSEp2YW1W\namRERVBNQTBHQTFVRUN4TUdabVZrYlhObk1ROHdEUVlEVlFRREV3Wm1aV1J0YzJjeER6QU5CZ05W\nCkJDa1RCbVpsWkcxelp6RW1NQ1FHQ1NxR1NJYjNEUUVKQVJZWFlXUnRhVzVBWm1Wa2IzSmhjSEp2\nYW1WamRDNXYKY21lQ0NRRGpVQjVIVHhjZVJUQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFM\nQmdOVkhROEVCQU1DQjRBdwpEUVlKS29aSWh2Y05BUUVGQlFBRGdZRUFRRnhlRGdCNHU0VHpDVHl3\nb25ZVlM5QnU0d28zUlZRdlpTc1lRQ1BECkRlWUVxeHVmcVJuTXFnbEp0OVlPR3ZuWk9OYWFYZ2ZY\nMkNJM3lLQ1AxV0ZXdEdIWFZkWjdDWWRiRVdZdTJZR2sKK2s5eGIrUjNUamZtNzFsWnU0cW1MWCs4\nMjJML0x4QzRWTlF0U3A5K3ZScjhkcXAySVdZSVpVMm01Vnh2cWhVMgowdFE9Ci0tLS0tRU5EIENF\nUlRJRklDQVRFLS0tLS0K\n', u'i': 26, u'timestamp': 1445258988, u'msg_id': u'2015-e722cd38-977e-4c27-83f0-41b774301ee8', u'crypto': u'x509', u'topic': u'org.fedoraproject.prod.pkgdb.package.new', u'signature': u'QwYMFMwMfXfi+V/Axl5L6QKD1Xv9+sjSA5rlV+OAehxgiIq4CjKDPZsMIysGybNWhByuks0YsjgT\n8hYXL58uaYxG7w5l1Ul/YdJGymqjN4nJNYp1+VZcZrCVRqDwc2zcQXRlHZsxjYbDC1lEp9RmifTd\ni8txC8RY1D+jRFQEXhY=\n', u'msg': {u'package_listing': {u'status': u'Approved', u'point_of_contact': u'mskalick', u'package': {u'status': u'Approved', u'upstream_url': u'https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey', u'koschei_monitor': False, u'monitor': True, u'summary': u'JavaScript interpreter and libraries', u'name': u'mozjs38', u'acls': [], u'creation_date': 1445258987.0, u'review_url': u'https://bugzilla.redhat.com/1269539', u'description': u"JavaScript is the Netscape-developed object scripting language used in millions of web pages and server applications worldwide. Netscape's JavaScript is a super set of the ECMA-262 Edition 3 (ECMAScript) standard scripting language, with only mild differences from the published standard."}, u'collection': {u'status': u'Under Development', u'dist_tag': u'.fc24', u'koji_name': u'rawhide', u'name': u'Fedora', u'version': u'devel', u'branchname': u'master'}, u'critpath': False, u'status_change': 1445258987.0}, u'package_name': u'mozjs38', u'agent': u'kevin'}}, 'topic': u'org.fedoraproject.prod.pkgdb.package.new'}
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 184, in _work
    self.consume(message)
  File "/root/the-new-hotness/hotness/consumers.py", line 143, in consume
    self.handle_new_package(msg, listing['package'])
  File "/root/the-new-hotness/hotness/consumers.py", line 444, in handle_new_package
    anitya.login(self.anitya_username, self.anitya_password)
  File "/root/the-new-hotness/hotness/anitya.py", line 202, in login
    raise AnityaException(output['message'])
AnityaException: Authentication failed
[2015-10-19 12:50:07][    fedmsg    INFO] Handling koji scratch msg u'2015-a92108ea-ae1c-4d4e-829a-2c13f143d215'
~~~

It seems that there was a problem with authentication process.
I would suggest to use not traceback but some logging error.

**Comment by ralphbean** [comment] 2015-10-19 14:45
I dunno, I find the traceback pretty helpful.  It tells us right where the error is.  (Plus, with our production setup, it emails all tracebacks to the sysadmins and developers for inspection).

Did you have valid FAS credentials in your ``fedmsg.d/`` config for https://release-monitoring.org?

**Comment by ralphbean** [comment] 2016-04-06 13:26
I'm going to close this one as "not a bug".  Since the-new-hotness is a server-side component, imho I think its OK to have tracebacks show up.  They're quite helpful for debugging.

Client side tools (on the other hand) should arguably hide tracebacks and print succinct error messages.

**Closed by ralphbean** 2016-04-06 13:26 UTC
