### ISSUE TITLE
If new hotness is slower than the package maintainer, and there is already a real build, the-new-hotness errors out.

### ISSUE THREAD

**Issue by jhdulaney** [fedora-infra/the-new-hotness#162] opened 2017-02-16 04:52 UTC
See bug 1422709

I happened to know the qtile release was coming, and got a real build into Rawhide before the-new-hotness detected the release; the-new hotness tried to perform a scratch build but errored out rather than fail gracefully and set the bug appropriately.

**Comment by ignatenkobrain** [comment] 2017-02-16 05:41
You mean like this? https://bugzilla.redhat.com/show_bug.cgi?id=1422703#c1

**Comment by jeremycline** [comment] 2017-02-16 09:41
Thanks for the report, @jhdulaney!

I checked the logs and the root cause is because release-monitoring.org is finding [versions prefixed with a v](https://release-monitoring.org/project/6503/) and then the-new-hotness drops that into the version field which produces a URL that 404s:
```
Feb 16 00:19:10 hotness01.phx2.fedoraproject.org fedmsg-hub[4523]: Getting https://github.com/qtile/qtile/archive/vv0.10.7.tar.gz to ./vv0.10.7.tar.gz
Feb 16 00:19:10 hotness01.phx2.fedoraproject.org fedmsg-hub[4523]: stderr:
Feb 16 00:19:10 hotness01.phx2.fedoraproject.org fedmsg-hub[4523]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Feb 16 00:19:10 hotness01.phx2.fedoraproject.org fedmsg-hub[4523]: Dload  Upload   Total   Spent    Left  Speed
Feb 16 00:19:10 hotness01.phx2.fedoraproject.org fedmsg-hub[4523]: [155B blob data]
Feb 16 00:19:10 hotness01.phx2.fedoraproject.org fedmsg-hub[4523]: 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Feb 16 00:19:10 hotness01.phx2.fedoraproject.org fedmsg-hub[4523]: curl: (22) The requested URL returned error: 404 Not Found
```
Given that, I'm going to close this a duplicate of #160.

The error message on that issue is very vague and is meant for truly unexpected events. I've improved the messages somewhat in #161 and in the future for this situation you'll see a comment along the lines of:
```
An HTTP error occurred downloading the package's new Source URLs: curl: (22) The requested URL returned error: 404 Not Found
```
Further improvements can definitely be made.

This problem is a very good argument for automatically stripping 'v' from releases automatically in Anitya (https://github.com/release-monitoring/anitya/issues/374).

**Closed by jeremycline** 2017-02-16 09:41 UTC
