### ISSUE TITLE
Bugzillas created by Reporter: upstream-release-monitoring@fedoraproject.org sometimes misses the last comment 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/the-new-hotness#313] opened 2021-01-01 14:02 UTC
https://bugzilla.redhat.com/show_bug.cgi?id=1911559 what happened to build it build ok or not ? 
https://bugzilla.redhat.com/show_bug.cgi?id=1909499 here replied with build not ok .
https://bugzilla.redhat.com/show_bug.cgi?id=1906457 what happened to build it build ok or not ?  

sometimes but often upstream-release-monitoring@fedoraproject.org doesn't do the comment number 2 .

**Comment by sergiomb2** [comment] 2021-01-02 20:55
Happened today https://bugzilla.redhat.com/show_bug.cgi?id=1912002

I can see the build went well in koji [1] but would be better have the comment update on bugzilla ... 

Thanks

[1]
https://koji.fedoraproject.org/koji/tasks?state=all&owner=the-new-hotness/release-monitoring.org&view=tree&method=all&order=-id
https://koji.fedoraproject.org/koji/taskinfo?taskID=58778707

**Comment by Zlopez** [comment] 2021-01-04 08:54
This looks like there is something more sinister going on, because the-new-hotness should also update bugzilla ticket when the scratch build is started.

**Comment by Zlopez** [comment] 2021-01-04 15:17
The issue is now fixed, it was happening, because the-new-hotness has two consumers running in production and both of them are using the dogpile local cache for saving the id of started build, but sometimes the other instance received the message that the build was completed.

I reduced the number of instances from 2 to 1.

**Closed by Zlopez** 2021-01-04 15:17 UTC
Labels: bug
