### ISSUE TITLE
 A bug was filed against mongoengine saying there was a newer version when there wasn't

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/the-new-hotness#131] opened 2016-11-14 01:06 UTC
This bug got filed against python-mongoengine, saying there was a new upstream release of 0.10.6:

https://bugzilla.redhat.com/show_bug.cgi?id=1389902

0.10.6 came out in January, and Fedora 24, 25, and Rawhide already have it.

**Comment by jeremycline** [comment] 2016-11-15 19:04
Hmm, I have a feeling this was caused by the latest Anitya release. I believe @pypingou put it in prod the same day that bug got filed. You can see release-engineering.org [thinks there was a recent v0.10.6](https://release-monitoring.org/project/8474/) release even though there was already a 0.10.6 release. This looks similar to https://github.com/fedora-infra/anitya/issues/372. I'm not sure about the root cause of https://github.com/fedora-infra/anitya/issues/372 since I can't reproduce it locally with master or the 0.10 tag, but clearly it's a thing that's happening.

**Comment by bowlofeggs** [comment] 2016-11-17 03:48
Thanks for the note @jeremycline! Do you think we should close this bug, or is the bug some interaction between Anitya and the-new-hotness?

**Comment by jeremycline** [comment] 2016-11-17 16:34
I think closing it makes the most sense to me because I don't think we want to try to be clever in the-new-hotness about whether or not we should build a new release. If Anitya says it's a new release, we should trust it (and fix Anitya when it lies).

**Closed by jeremycline** 2016-11-17 16:34 UTC
Labels: bug
