### ISSUE TITLE
GenericError: File upload failed

### ISSUE THREAD

**Issue by mcatanzaro** [fedora-infra/the-new-hotness#541] opened 2022-12-01 15:20 UTC
Looks like something went wrong [here](https://bugzilla.redhat.com/show_bug.cgi?id=2149398#c1):

```
GenericError: File upload failed: cli-build/1669750876.4140136.ZlQwdMqU/uncrustify-0.76.0-1.fc36.src.rpm
Traceback:
  File "/usr/local/lib/python3.10/site-packages/hotness/use_cases/package_scratch_build_use_case.py", line 56, in build
    result = self.builder.build(request.package, request.opts)
  File "/usr/local/lib/python3.10/site-packages/hotness/builders/koji.py", line 198, in build
    output["build_id"] = self._scratch_build(session, package.name, srpm)
  File "/usr/local/lib/python3.10/site-packages/hotness/builders/koji.py", line 451, in _scratch_build
    session.uploadWrapper(source, serverdir)
  File "/usr/lib/python3.10/site-packages/koji/__init__.py", line 3083, in uploadWrapper
    self.fastUpload(localfile, path, name, callback, blocksize, overwrite, volume=volume)
  File "/usr/lib/python3.10/site-packages/koji/__init__.py", line 3018, in fastUpload
    raise GenericError("File upload failed: %s/%s" % (path, name))
```

**Comment by mattdm** [comment] 2022-12-02 14:51
Same: https://bugzilla.redhat.com/show_bug.cgi?id=2149088#c4

**Comment by Zlopez** [comment] 2022-12-05 13:59
The error from the koji doesn't say much. It could be caused by anything.
Only solution for this that comes to my mind is to add some retry, when this error happens.
I must look if the `uploadWrapper` in the `koji` library has some options like that.
According to `koji` code `uploadWrapper` doesn't allow that and the error means that the [file wasn't found on the destination when checking](https://pagure.io/koji/blob/master/f/koji/__init__.py#_3032). So nothing helpful at all.

**Comment by dreua** [comment] 2022-12-28 16:36
Same: https://bugzilla.redhat.com/show_bug.cgi?id=2149537

Some more information / build logs would be nice if those cases.

**Comment by Zlopez** [comment] 2023-01-09 11:18
@dreua I agree, but this happens before the build itself and the koji doesn't provide more information. So I can't do much about this :-/

**Comment by Zlopez** [comment] 2023-03-08 14:30
With https://github.com/fedora-infra/the-new-hotness/pull/554 I added patch to be attached to bugzilla ticket as well, so there would be more information about what exactly the-new-hotness changed.

So I'm closing this because we are now returning more info when the error happens.

**Closed by Zlopez** 2023-03-08 14:30 UTC
Labels: type.bug

**Comment by AsciiWolf** [comment] 2023-05-02 09:36
Same issue: https://bugzilla.redhat.com/show_bug.cgi?id=2192158#c1

Still the same generic error without any details/patches included.

**Comment by Zlopez** [comment] 2023-05-02 11:00
The change should be live now, I need to look why it didn't catch that up.

**Comment by Zlopez** [comment] 2023-05-02 12:22
Unfortunately the logs were cleared at 1st May, so I can't check what exactly happened. I will try to monitor it and maybe I will catch it.

**Comment by Zlopez** [comment] 2023-05-02 12:29
Ok, so I found another project with the issue that happened during the scratch build and the patch is there https://bugzilla.redhat.com/show_bug.cgi?id=2192421, so this works at least in some cases.

**Comment by Zlopez** [comment] 2023-05-02 12:36
And in this case it even worked for the same error https://bugzilla.redhat.com/show_bug.cgi?id=2185981. I just wonder if your issue wasn't before I deployed version 1.2.3.
