### ISSUE TITLE
django package can't find source

### ISSUE THREAD

**Issue by traylenator** [fedora-infra/the-new-hotness#563] opened 2023-05-05 13:21 UTC
Hi,

The django package fails with:

DownloadException: The specfile contains a Source URL with an unknown protocol; it shouldbe "https", "http", or "ftp".

despite:

spectool -g python-django.spec 
Downloading: https://files.pythonhosted.org/packages/source/D/Django/Django-4.2.1.tar.gz

https://bugzilla.redhat.com/show_bug.cgi?id=2059544

Does the 

%global ver 4.1.7 confuse things ... probably.

https://src.fedoraproject.org/rpms/python-django/blob/rawhide/f/python-django.spec

I can't see the attachment with the diff to check.

**Comment by Zlopez** [comment] 2023-05-23 08:30
After trying the process manually it seems that the issue is in `rpmdev-bumpspec` command.
It seems that it can't work correctly with the macros that are used in Django spec file.
I cloned the dist-git repository and tried to run `rpmdev-bumpspec --new 4.1.7 -c "Test" -u "test@test.com" python-django.spec` and it did this changes in specfile:
```
diff --git a/python-django.spec b/python-django.spec
index be0e99c..c94f79a 100644
--- a/python-django.spec
+++ b/python-django.spec
@@ -3,7 +3,7 @@ Name:           python-django
 %global         ver 4.1.7
 #global         pre ...
 %global         real_version %{ver}%{?pre:%{pre}}
-Version:        %{ver}%{?pre:~%{pre}}
+Version:        %{ver}%{?pre:4.1.7
 Release:        1%{?dist}
 Summary:        A high-level Python Web framework
 
@@ -136,6 +136,9 @@ cd tests
 
 
 %changelog
+* Tue May 23 2023 test@test.com
+- Test
+
 * Mon Feb 13 2023 Matthias Runge <mrunge@redhat.com> - 4.1.7-1
 - update to 4.1.7 (rhbz#2169312)
```

And if you try to run the `spectool -g` on that:
```
error: line 6: unclosed macro or bad line continuation
RPM Failed to parse spec file.
```

This is where the error comes from. But I noticed that another thing, when the `DownloadException` error is thrown it wouldn't provide the patch file, I will fix that, but the issue with `rpmdev-bumpspec` needs to be solved [upstream](https://pagure.io/rpmdevtools). @traylenator Could you create it there?

**Comment by Zlopez** [comment] 2023-05-23 08:32
Closing this one as there is nothing I can do on the hotness side.

**Closed by Zlopez** 2023-05-23 08:32 UTC
Labels: investigate

**Comment by traylenator** [comment] 2023-05-25 07:29
@Zlopez thanks for your investigation.

As for rpmbump it looks to be a case of the existing:

https://pagure.io/rpmdevtools/issue/18

where I've just added an extra note.

Indeed changing how python-django is done may be easier.
