### ISSUE TITLE
Exclude pre-release versions from creating a BZ

### ISSUE THREAD

**Issue by duritong** [fedora-infra/the-new-hotness#320] opened 2021-04-16 07:18 UTC
Since a while there are BZs created for pre-releases, e.g. https://bugzilla.redhat.com/show_bug.cgi?id=1950184 the version is clearly flagged as pre-release: https://release-monitoring.org/project/4991/

But there does not seem to be a way to exclude pre-release versions from creating a BZ?

**Comment by Zlopez** [comment] 2021-04-16 07:54
The pre-release versions are only recognized by Anitya (release-monitoring.org) right now, there is a plan to allow packagers to change the settings in src.fedoraproject.org, but for now the-new-hotness is behaving the same as is always did.

**Comment by gotmax23** [comment] 2021-12-02 03:29
Is there any movement on this? Fedora packagers already receive a lot of email, so it would be nice if we had the ability to prevent the-new-hotness from creating unwanted bugs for pre-releases.

Thanks!

**Comment by Zlopez** [comment] 2022-05-05 11:54
Duplicate of #99

**Closed by Zlopez** 2022-05-05 11:54 UTC
Labels: type.feature
