### ISSUE TITLE
"Bad source" error for a package (./concurrent-ruby-1.1.10-specs.tar.gz: No such file or directory)

### ISSUE THREAD

**Issue by claviola** [fedora-infra/the-new-hotness#442] opened 2022-04-20 17:27 UTC
On [bugzilla 2066526](https://bugzilla.redhat.com/show_bug.cgi?id=2066526) there's a build which immediately failed like this:

`error: Bad source: ./concurrent-ruby-1.1.10-specs.tar.gz: No such file or directory`

I know nothing about the-new-hotness, but I assume it would be trying to automatically use the specs from the older version with the new one, and this process somehow failed.

It'd also be interesting to be able to trigger a retry if it was a transient issue.

**Comment by Zlopez** [comment] 2022-04-20 19:55
Duplicate of #422

**Closed by Zlopez** 2022-04-20 19:55 UTC

**Comment by voxik** [comment] 2022-04-21 10:57
Please note that the `concurrent-ruby-1.1.10-specs.tar.gz` tarball is custom created tarball with the instructions above the source line. So ATM, the only option is to disable the rebuild after new release is identified. There are other options such as \[[1]\] considered, but I would not be overly optimistic.


[1]: https://pagure.io/packaging-committee/issue/1132#comment-769233
