### ISSUE TITLE
Upload fails with python trace whilst uploading mg srpm

### ISSUE THREAD

**Issue by hboetes** [fedora-infra/the-new-hotness#557] opened 2023-04-06 20:25 UTC
For reference: https://bugzilla.redhat.com/show_bug.cgi?id=1941656#c21

```
Scratch build failed. Details below:

GenericError: File upload failed: cli-build/1680794132.2614074.DUsbvvro/mg-20230406-1.fc36.src.rpm
Traceback:
  File "/usr/local/lib/python3.10/site-packages/hotness/use_cases/package_scratch_build_use_case.py", line 56, in build
    result = self.builder.build(request.package, request.opts)
  File "/usr/local/lib/python3.10/site-packages/hotness/builders/koji.py", line 198, in build
    output["build_id"] = self._scratch_build(session, package.name, srpm)
  File "/usr/local/lib/python3.10/site-packages/hotness/builders/koji.py", line 451, in _scratch_build
    session.uploadWrapper(source, serverdir)
  File "/usr/lib/python3.10/site-packages/koji/__init__.py", line 3110, in uploadWrapper
    self.fastUpload(localfile, path, name, callback, blocksize, overwrite, volume=volume)
  File "/usr/lib/python3.10/site-packages/koji/__init__.py", line 3034, in fastUpload
    raise GenericError("File upload failed: %s/%s" % (path, name))

If you think this issue is caused by some bug in the-new-hotness, please report it on the-new-hotness issue tracker: https://github.com/fedora-infra/the-new-hotness/issues
```

**Comment by Zlopez** [comment] 2023-04-13 09:13
This is a duplicate of https://github.com/fedora-infra/the-new-hotness/issues/541 and I can't do much about it. It just means that the koji library wasn't able to upload the file. I will leave this ticket open, because I would need to add some way to handle this error more gracefully in hotness.

**Comment by hboetes** [comment] 2023-04-13 11:25
OK, thanks.

**Closed** 2023-05-23 10:21 UTC
Labels: type.bug
