### ISSUE TITLE
New version notifications not reported

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/the-new-hotness#205] opened 2018-11-23 08:12 UTC
It seems the-new-hotness doesn't report new versions to Bugzilla anymore.
https://release-monitoring.org/project/9030/
Despite several new versions were detected by Anitya, no bug has been filled. I can't also find any related message in fedmsg:
https://apps.fedoraproject.org/datagrepper/raw?package=ccdciel
so I'm not sure if it's a t-n-h issue or Anitya which isn't emitting fedmsg messages.

Also, in the old pkgdb there was the way to choose if enable or not the new version notification. Is there anything similar with the new pagure based git system? I can't found anything in any documentation.

**Comment by Zlopez** [comment] 2018-11-23 08:54
This is a known issue, probably caused by fedmsg. We are currently working on migration from fedmsg to fedora-messaging. See https://github.com/release-monitoring/anitya/issues/638

About the notifications look here - https://pagure.io/releng/fedora-scm-requests/#anitya

**Comment by Zlopez** [comment] 2019-02-21 14:08
This is already solved. Closing.

**Closed by Zlopez** 2019-02-21 14:08 UTC
