### ISSUE TITLE
Missing BZ ticket for Ruby update

### ISSUE THREAD

**Issue by voxik** [fedora-infra/the-new-hotness#307] opened 2020-10-05 15:59 UTC
There was no BZ ticket reported for Ruby 2.7.2 update:

https://release-monitoring.org/project/4223/
https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&product=Fedora&product=Fedora%20EPEL&component=ruby

**Comment by Zlopez** [comment] 2020-10-06 10:29
I did some investigation, the [message from Anitya](https://apps.fedoraproject.org/datagrepper/id?id=2020-efc02225-a37a-4913-9957-ced1cd4ab954&is_raw=true&size=extra-large) about new version was sent correctly.
But I can't access the old logs for the-new-hotness because of the [expired certificate for Kibana](https://pagure.io/fedora-infrastructure/issue/9377)

I will try to reproduce the issue locally.

**Comment by Zlopez** [comment] 2020-10-06 11:44
I tried to reproduce it locally and the [PDC is returning 503](https://pagure.io/fedora-infrastructure/issue/9376) right now.

This [url](https://pdc.fedoraproject.org/rest_api/v1/component-branches/?name=master&global_component=ruby&type=rpm&active=True) is returning 503, which the-new-hotness evaluates as retired package :-(

I will try it later when the PDC will run again, because this probably wasn't the issue when the message was consumed by the-new-hotness when the 2.7.2 update was released.

**Comment by Zlopez** [comment] 2020-10-06 15:30
The issue with PDC is resolved and I was able to continue the investigation, the current version according to [mdapi](https://mdapi.fedoraproject.org/koji/srcpkg/ruby) is `6.2.1-134.fc33` which is much higher than `2.7.2`.

As I see it there is issue in mdapi, because the https://src.fedoraproject.org/rpms/ruby shows that latest version is `ruby-2.7.1-134.fc33`

**Comment by Zlopez** [comment] 2020-10-06 15:32
I'm closing this because the issue is not in the-new-hotness, feel free to open it if needed

**Closed by Zlopez** 2020-10-06 15:32 UTC
Labels: investigate

**Comment by voxik** [comment] 2020-10-06 19:45
Ah, thx for analysis. I have reported this against mdapi:

https://pagure.io/mdapi/issue/115
